/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PGA_1.h"
#include "pga_in_aliases.h"
#include "pga_in.h"
#include "pga_out_aliases.h"
#include "pga_out.h"
#include "pga_ref_aliases.h"
#include "pga_ref.h"
#include "ADC_DelSig_1.h"
#include "isr_adc_eoc.h"
#include "Pin_debug1_aliases.h"
#include "Pin_debug1.h"
#include "Pin_adc_eoc_aliases.h"
#include "Pin_adc_eoc.h"
#include "DVDAC_1.h"
#include "Pin_dac_aliases.h"
#include "Pin_dac.h"
#include "UART_1.h"
#include "Pin_Button_aliases.h"
#include "Pin_Button.h"
#include "Pin_Led_aliases.h"
#include "Pin_Led.h"
#include "Uart_Rx_aliases.h"
#include "Uart_Rx.h"
#include "SPI_led.h"
#include "SPI_led_PVT.h"
#include "Pin_LE_aliases.h"
#include "Pin_LE.h"
#include "mosi_aliases.h"
#include "mosi.h"
#include "sclk_aliases.h"
#include "sclk.h"
#include "miso_aliases.h"
#include "miso.h"
#include "Pin_buttDown_aliases.h"
#include "Pin_buttDown.h"
#include "Pin_buttUp_aliases.h"
#include "Pin_buttUp.h"
#include "SS_aliases.h"
#include "SS.h"
#include "Pin_OE_aliases.h"
#include "Pin_OE.h"
#include "Clock_1.h"
#include "isr_Pin_buttUp.h"
#include "isr_Pin_buttDown.h"
#include "Clock_debounce.h"
#include "SPI_adc.h"
#include "SPI_adc_PVT.h"
#include "miso_1_aliases.h"
#include "miso_1.h"
#include "mosi_1_aliases.h"
#include "mosi_1.h"
#include "sclk_1_aliases.h"
#include "sclk_1.h"
#include "SS_1_aliases.h"
#include "SS_1.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "DVDAC_1_DMA_dma.h"
#include "DVDAC_1_VDAC8.h"
#include "DVDAC_1_IntClock.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

